module.exports = [
    {
        id: 1,
        name: 'The Avengers',
        genre: ['science fiction', 'action', 'superheroes'],
        dateRelease: '26 de abril de 2012',
        country: '',
        director: 'Joss Whedon',
        description: 'El director de la Agencia SHIELD decide reclutar a un equipo para salvar al mundo de un desastre casi seguro cuando un enemigo inesperado surge como una gran amenaza para la seguridad mundial.',
        duration: '',
        awards: [''],
        iconSrc: {web: true, src: 'https://img.icons8.com/offices/50/000000/avengers.png'}, //el tamaño se cambia con el número ..offices/numero/000...
        imgFile: 'theAvengers.jpg',
        urlNetflix: '',
        urlYoutube: ''
    },
    {
        id: 2,
        name: 'Spider-Man',
        genre: ['action', 'superheroes', 'science fiction', 'exciting'],
        dateRelease: '15 de mayo de 2002 (Argentina)',
        country: '',
        director: 'Sam Raimi',
        description: 'Un tímido estudiante se vuelve en un luchador contra el crimen, desde que la picadura de una araña mutante le da poderes extraordinarios.',
        duration: '2h 1min',
        awards: ["People's Choice a la Película Favorita"],
        iconSrc: {},
        imgFile: 'spiderman.jpg',
        urlNetflix: 'https://www.netflix.com/watch/60004481?trackId=13752289&tctx=0%2C0%2Cee6ef0bfff953740d08b534bebd3b3713d579887%3Ae09a75f9b582a8dfded619f56463d40900d234b1%2C%2C',
        urlYoutube: ''
    },
    {
        id: 3,
        name: 'Toy Story 3',
        genre: ['trending', 'comedy'],
        dateRelease: '2003',
        country: '',
        director: 'Jhon Lasseter',
        description: '',
        duration: '',
        awards: [''],
        iconSrc: {},
        imgFile: 'toyStory.jpg',
        urlNetflix: '',
        urlYoutube: ''
    },
    {
        id: 4,
        name: 'Up!',
        genre: ['popular', 'comedy', 'trending'],
        dateRelease: '1998',
        country: '',
        director: '',
        description: '',
        duration: '',
        awards: [''],
        iconSrc: {},
        imgFile: 'up.jpg',
        urlNetflix: '',
        urlYoutube: ''   
    },
    {
        id: 5,
        name: '3 metros sobre el cielo',
        genre: ['popular', 'romance', 'drama'],
        dateRelease: '3 de diciembre de 2010',
        country: 'España',
        director: 'Fernando González Molina',
        description: '',
        duration: '',
        awards: [''],
        iconSrc: {},
        imgFile: '3metrosSobreElCielo.jpg',
        urlNetflix: '',
        urlYoutube: ''
    },
    {
        id: 6,
        name: 'Titanic',
        genre: ['popular', 'drama', 'romance', 'classic'],
        dateRelease: '5 de febrero de 1998',
        country: '',
        director: 'James Cameron',
        description: '',
        duration: '',
        awards: [''],
        iconSrc: {},
        imgFile: 'titanic.jpg',
        urlNetflix: '',
        urlYoutube: ''
    },
    {
        id: 7,
        name: 'Contratiempo',
        genre: ['suspense'],
        dateRelease: '10 de agosto de 2017',
        country: 'España',
        director: 'Oriol Paulo',
        description: '',
        duration: '',
        awards: [''],
        iconSrc: {},
        imgFile: 'contratiempo.jpg',
        urlNetflix: 'https://www.netflix.com/watch/80093106?trackId=13752289&tctx=0%2C0%2C2095f8ce8d0626ec7cdf0f05b9d93f094de66563%3A3aa3566af4557216e7204e85d7e2b9d61ff948a4%2C%2C',
        urlYoutube: ''
    },
    {
        id: 8,
        name: 'Batman, el Caballero de la Noche Asciende',
        genre: ['trending', 'suspense', 'action'],
        dateRelease: '26 de julio de 2012',
        country: '',
        director: 'Christopher Nolan',
        description: '',
        duration: '',
        awards: [''],
        iconSrc: {},
        imgFile: 'batmanElCaballeroAsc.jpg',
        urlNetflix: '',
        urlYoutube: ''
    },
    {
        id: 9,
        name: 'Thor',
        genre: ['science fiction', 'action', 'superheroes'],
        dateRelease: '17 de abril de 2011',
        country: 'Estados Unidos',
        director: 'Kenneth Branagh',
        description: 'Tras desatar una antigua guerra, el codicioso guerrero Thor es desterrado a la Tierra por su padre para que viva entre los hombres y descubra así el verdadero sentido de la humildad. Allí, sin sus poderes, Thor deberá enfrentarse a las fuerzas más oscuras que su mayor enemigo le enviará desde Asgard.',
        duration: '1h 55min',
        awards: [''],
        iconSrc: {web: true, src: 'https://img.icons8.com/material-rounded/48/000000/law.png'},
        imgFile: 'thor.jpg',
        urlNetflix: 'https://www.netflix.com/watch/70141586?trackId=13752289&tctx=1%2C1%2C4cf5b366d4f4705bfb71a19bb69ae4e12611446d%3A0c331564926727b9d5f866ebd8e77a9f01237b8e%2C%2C',
        urlYoutube: 'https://www.youtube.com/watch?v=JOddp-nlNvQ'
    },
    {
        id: 10,
        name: 'El gran Gatsby',
        genre: ['drama', 'romance'],
        dateRelease: '16 de mayo de 2013',
        country: '',
        director: 'Baz Luhrmann',
        description: 'Nick Carraway (Tobey Maguire), nativo del Medio Oeste, llega a Nueva York en 1922 en busca del sueño americano. Nick, un aspirante a escritor, se muda al lado del millonario Jay Gatsby (Leonardo DiCaprio) y al otro lado de la bahía de su prima Daisy (Carey Mulligan) y su esposo mujeriego, Tom (Joel Edgerton). Nick se involucra en un mundo cautivador de riqueza y -- mientras observa sus ilusiones y engaños -- escribe una historia de amor imposible, sueños y tragedia.',
        duration: '2h 23m',
        awards: ['Óscar al mejor diseño de producción |', 'Óscar al mejor diseño de vestuario'],
        iconSrc: {web: true, src: 'https://img.icons8.com/material-rounded/48/000000/average-2.png'},
        imgFile: 'elGranGatsby.jpg',
        urlNetflix: 'https://www.netflix.com/watch/70244437?trackId=14170286&tctx=2%2C2%2C93c5099b-8f84-4684-a59e-8ced44539a02-57642481%2C4fd17f35-2bae-411a-9903-be44945770d4_29187538X3XX1584755874162%2C4fd17f35-2bae-411a-9903-be44945770d4_ROOT',
        urlYoutube: 'https://www.youtube.com/watch?v=TYMMOjBUPMM'
    },
];